routes/web.php
<?php

use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Artisan::call('storage:link');

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', [App\Http\Controllers\FrontOfficeController::class, 'indexFrontOffice']);

Route::get('/contacter-nous', [App\Http\Controllers\FrontOfficeController::class, 'nousContacter'])->name('contacter-nous');

Route::get('/blog', [App\Http\Controllers\FrontOfficeController::class, 'indexBlog'])->name('blog');

Route::get('/detailblog/{slug}', [App\Http\Controllers\FrontOfficeController::class, "showBlog"]);

Route::get('/a-propos', [App\Http\Controllers\FrontOfficeController::class, 'indexAbout'])->name('a-propos');

Route::get('/prise-de-rendez-vous', [App\Http\Controllers\FrontOfficeController::class, 'appointmentPages'])->name('prise-de-rendez-vous');

Route::get('/irm', [App\Http\Controllers\FrontOfficeController::class, 'irmPage'])->name('irm');

Route::get('/biopsie', [App\Http\Controllers\FrontOfficeController::class, 'biopsiePage'])->name('biopsie');

Route::get('/echographie', [App\Http\Controllers\FrontOfficeController::class, 'echographiePage'])->name('echographie');

Route::get('/scanner', [App\Http\Controllers\FrontOfficeController::class, 'scannerPage'])->name('scanner');

Route::get('/mammographie', [App\Http\Controllers\FrontOfficeController::class, 'mammographiePage'])->name('mammographie');

Route::get('/radiographie', [App\Http\Controllers\FrontOfficeController::class, 'radiographiePage'])->name('radiographie');

Route::get('/bilan-sante', [App\Http\Controllers\FrontOfficeController::class, 'healhCheckPage'])->name('bilan-sante');

Route::get('/analyse-mediacale', [App\Http\Controllers\FrontOfficeController::class, 'medicalAnalysPage'])->name('analyse-mediacale');

Route::post('/footer', [App\Http\Controllers\NewslettersController::class, "addEmail"])->name('footer');

Route::post('/appointmentess', [App\Http\Controllers\AppointmentController::class, "SendAppointment"])->name('appointmentess');

Auth::routes([
    'register' => false, // Registration Routes...
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...
  ]);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::resource('slides', App\Http\Controllers\SlideController::class);

Route::resource('medicalSpecialties', App\Http\Controllers\MedicalSpecialtiesController::class);

Route::resource('appointments', App\Http\Controllers\AppointmentController::class);

Route::resource('blogs', App\Http\Controllers\BlogController::class);

Route::resource('newsletters', App\Http\Controllers\NewslettersController::class);

Route::resource('testimonials', App\Http\Controllers\TestimonialsController::class);

Route::resource('medicalCheckups', App\Http\Controllers\MedicalCheckupsController::class);

Route::resource('videoStores', App\Http\Controllers\VideoStoresController::class);

Route::post('ckeditor/upload', [App\Http\Controllers\CKEditorController::class, "upload"])->name('upload');

app/Http/Controllers/MedicalSpecialtiesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateMedicalSpecialtiesRequest;
use App\Http\Requests\UpdateMedicalSpecialtiesRequest;
use App\Repositories\MedicalSpecialtiesRepository;
use App\Http\Controllers\AppBaseController;
use App\Models\MedicalSpecialties;
use Illuminate\Http\Request;
use Flash;
use Response;

class MedicalSpecialtiesController extends AppBaseController
{
    /** @var  MedicalSpecialtiesRepository */
    private $medicalSpecialtiesRepository;

    public function __construct(MedicalSpecialtiesRepository $medicalSpecialtiesRepo)
    {
        $this->medicalSpecialtiesRepository = $medicalSpecialtiesRepo;
    }

    /**
     * Display a listing of the MedicalSpecialties.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        // $medicalSpecialties = $this->medicalSpecialtiesRepository->all();
        $medicalSpecialties = MedicalSpecialties::orderBy('id', 'desc')->paginate(10);

        return view('medical_specialties.index')
            ->with('medicalSpecialties', $medicalSpecialties);
    }

    /**
     * Show the form for creating a new MedicalSpecialties.
     *
     * @return Response
     */
    public function create()
    {
        return view('medical_specialties.create');
    }

    /**
     * Store a newly created MedicalSpecialties in storage.
     *
     * @param CreateMedicalSpecialtiesRequest $request
     *
     * @return Response
     */
    public function store(CreateMedicalSpecialtiesRequest $request)
    {
        $input = $request->all();

        if ($request->hasFile('image'))
        {
            $destination_path = 'public/images';
            $image = $request->file('image');
            $image_name = $image->getClientOriginalName();
            $path = $request->file('image')->storeAs($destination_path, $image_name);

            $input['image'] = $image_name;
        }

        $medicalSpecialties = $this->medicalSpecialtiesRepository->create($input);

        Flash::success('Medical Specialties saved successfully.');

        return redirect(route('medicalSpecialties.index'));
    }

    /**
     * Display the specified MedicalSpecialties.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $medicalSpecialties = $this->medicalSpecialtiesRepository->find($id);

        if (empty($medicalSpecialties)) {
            Flash::error('Medical Specialties not found');

            return redirect(route('medicalSpecialties.index'));
        }

        return view('medical_specialties.show')->with('medicalSpecialties', $medicalSpecialties);
    }

    /**
     * Show the form for editing the specified MedicalSpecialties.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $medicalSpecialties = $this->medicalSpecialtiesRepository->find($id);

        if (empty($medicalSpecialties)) {
            Flash::error('Medical Specialties not found');

            return redirect(route('medicalSpecialties.index'));
        }

        return view('medical_specialties.edit')->with('medicalSpecialties', $medicalSpecialties);
    }

    /**
     * Update the specified MedicalSpecialties in storage.
     *
     * @param int $id
     * @param UpdateMedicalSpecialtiesRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateMedicalSpecialtiesRequest $request)
    {
        $medicalSpecialties = $this->medicalSpecialtiesRepository->find($id);

        if (empty($medicalSpecialties)) {
            Flash::error('Medical Specialties not found');

            return redirect(route('medicalSpecialties.index'));
        }

        $input = $request->all();

        if ($request->hasFile('image'))
        {
            $destination_path = 'public/images';
            $image = $request->file('image');
            $image_name = $image->getClientOriginalName();
            $path = $request->file('image')->storeAs($destination_path, $image_name);

            $input['image'] = $image_name;
        }

        $medicalSpecialties = $this->medicalSpecialtiesRepository->update($request->all(), $id);

        Flash::success('Medical Specialties updated successfully.');

        return redirect(route('medicalSpecialties.index'));
    }

    /**
     * Remove the specified MedicalSpecialties from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $medicalSpecialties = $this->medicalSpecialtiesRepository->find($id);

        if (empty($medicalSpecialties)) {
            Flash::error('Medical Specialties not found');

            return redirect(route('medicalSpecialties.index'));
        }

        $this->medicalSpecialtiesRepository->delete($id);

        Flash::success('Medical Specialties deleted successfully.');

        return redirect(route('medicalSpecialties.index'));
    }
}

resources/views/medical_specialties/create.blade.php
@extends('BackOffice_layouts.master_index')

@section('title')
    Nos Services Médicaux | {{ config('app.name') }}
@endsection

@section('content')

<div class="page-heading">
    <div class="page-title">
        <div class="row">
            <div class="col-12 col-md-6 order-md-1 order-last">
                <h3 style="color: white !important">Créer un Nouveau Service</h3>
                <p class="text-subtitle text-muted" style="color: white !important">Les informations sur le Service</p>
            </div>
        </div>
    </div>

    <section id="basic-horizontal-layouts">
        <div class="row match-height">
            <div class="col-md-12 col-12">
                <div class="card">
                    <div class="card-content">
                        <div class="card-body">
                            {!! Form::open(['route' => 'medicalSpecialties.store', 'class' => 'form', 'files' => true]) !!}
                                <div class="row">
                                    @include('medical_specialties.fields')
                                </div>
                            {!! Form::close() !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

</div>

@endsection

resources/views/medical_specialties/edit.blade.php
@extends('BackOffice_layouts.master_index')

@section('title')
    Nos Services Médicaux | {{ config('app.name') }}
@endsection

@section('content')

    <div class="page-heading">
        <div class="page-title">
            <div class="row">
                <div class="col-12 col-md-6 order-md-1 order-last">
                    <h3 style="color: white !important">Modifier le Service</h3>
                    <p class="text-subtitle text-muted" style="color: white !important">Les informations sur le Service</p>
                </div>
            </div>
        </div>

        <section id="basic-horizontal-layouts">
            <div class="row match-height">
                <div class="col-md-12 col-12">
                    <div class="card">
                        <div class="card-content">
                            <div class="card-body">
                                {!! Form::model($medicalSpecialties, ['route' => ['medicalSpecialties.update', $medicalSpecialties->id], 'method' => 'patch', 'files' => true]) !!}
                                    <div class="row">
                                        @include('medical_specialties.fields')
                                    </div>
                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

    </div>

@endsection

resources/views/medical_specialties/fields.blade.php
<!-- Title Field -->
<div class="col-md-6 col-12">
    <div class="form-group">
        {!! Form::label('title', 'Titre du projet:') !!}
        {!! Form::text('title', null, ['class' => 'form-control', 'placeholder' => 'Titre', 'onkeyup' => 'stringToSlug(this.value)']) !!}
    </div>
</div>

<!-- slug Field -->
<div class="col-md-6 col-12">
    <div class="form-group">
        {!! Form::label('slug', 'Slug:') !!}
        {!! Form::text('slug', null, ['class' => 'form-control', 'placeholder' => 'Slug', 'readonly']) !!}
    </div>
</div>

<!-- description Field -->
<div class="col-md-12">
    <div class="form-group">
        {!! Form::label('description', 'Description du Service:') !!}
        {!! Form::textarea('description', null, ['class' => 'form-control ckeditor', 'name' => 'description']) !!}
    </div>
</div>

<!-- image Field -->
<div class="col-md-6 col-12">
    <div class="form-group">
        {!! Form::label('image', 'Image de garde:') !!}
        {!! Form::file('image', ['class' => 'form-control', 'id' => 'formFile']) !!}
    </div>
</div>

<div class="row mt-3">
    <div class="col-md-12 col-12 order-md-1 order-last">
        <h3 style="color: black !important">Précaution Avant l'Examen</h3>
    </div>
</div>

<!-- Title Field -->
<div class="col-md-6 col-12">
    <div class="form-group">
        {!! Form::label('title', 'Titre du projet:') !!}
        {!! Form::text('title', null, ['class' => 'form-control', 'placeholder' => 'Titre', 'onkeyup' => 'stringToSlug(this.value)']) !!}
    </div>
</div>

<!-- slug Field -->
<div class="col-md-6 col-12">
    <div class="form-group">
        {!! Form::label('slug', 'Slug:') !!}
        {!! Form::text('slug', null, ['class' => 'form-control', 'placeholder' => 'Slug', 'readonly']) !!}
    </div>
</div>

<!-- description Field -->
<div class="col-md-12">
    <div class="form-group">
        {!! Form::label('description_prec_befor_exams', 'Description:') !!}
        {!! Form::textarea('description_prec_befor_exams', null, ['class' => 'form-control ckeditor', 'name' => 'description']) !!}
    </div>
</div>

<div class="row mt-3">
    <div class="col-md-12 col-12 order-md-1 order-last">
        <h3 style="color: black !important">Précaution Durant l'Examen</h3>
    </div>
</div>

<!-- Title Field -->
<div class="col-md-6 col-12">
    <div class="form-group">
        {!! Form::label('title', 'Titre du projet:') !!}
        {!! Form::text('title', null, ['class' => 'form-control', 'placeholder' => 'Titre', 'onkeyup' => 'stringToSlug(this.value)']) !!}
    </div>
</div>

<!-- slug Field -->
<div class="col-md-6 col-12">
    <div class="form-group">
        {!! Form::label('slug', 'Slug:') !!}
        {!! Form::text('slug', null, ['class' => 'form-control', 'placeholder' => 'Slug', 'readonly']) !!}
    </div>
</div>

<!-- description Field -->
<div class="col-md-12">
    <div class="form-group">
        {!! Form::label('description_prec_during_exams', 'Description:') !!}
        {!! Form::textarea('description_prec_during_exams', null, ['class' => 'form-control ckeditor', 'name' => 'description']) !!}
    </div>
</div>

<div class="col-12 d-flex justify-content-end mt-3">
    {!! Form::submit('Enregistré', ['class' => 'btn btn-danger me-1 mb-1']) !!}
    <a href="{{ route('medicalSpecialties.index') }}" class="btn btn-light-secondary me-1 mb-1">Annulé</a>
</div>

<script>
    function stringToSlug(str) {

        str = str.replace(/^\s+|\s+$/g, ''); // trim
        str = str.toLowerCase();

        // remove accents, swap ñ for n, etc
        var from = "àáäâèéëêìíïîòóöôùúüûñç·/_,:;";
        var to = "aaaaeeeeiiiioooouuuunc------";
        for (var i = 0, l = from.length; i < l; i++) {
            str = str.replace(new RegExp(from.charAt(i), 'g'), to.charAt(i));
        }

        str = str.replace(/[^a-z0-9 -]/g, '') // remove invalid chars
            .replace(/\s+/g, '-') // collapse whitespace and replace by -
            .replace(/-+/g, '-'); // collapse dashes

        // return str;
        document.getElementById("slug").value = str;
    }

    function showPercentage(val){
        if(val == 1){
            document.getElementById("div_percentage").style.display= 'block';
        }else{
            document.getElementById("div_percentage").style.display= 'none';
        }
    }

    function showSold(val){
        if(val == 1){
            document.getElementById("div_sold").style.display= 'block';
        }else{
            document.getElementById("div_sold").style.display= 'none';
        }
    }
</script>

resources/views/medical_specialties/index.blade.php
@extends('BackOffice_layouts.master_index')

@section('title')
    Nos Services Médicaux | {{ config('app.name') }}
@endsection

@section('content')

    <div class="page-heading">
        <div class="page-title">
            <div class="row">
                <div class="col-12 col-md-6 order-md-1 order-last">
                    <h3 style="color: white !important">Nos Services Médicaux</h3>
                    <p class="text-subtitle text-muted" style="color: white !important">La liste de tous nos Services Médicaux</p>
                </div>
                <div class="col-12 col-md-6 order-md-2 order-first">
                    <nav aria-label="breadcrumb" class="breadcrumb-header float-start float-lg-end">
                        <ol class="breadcrumb">
                            <a class="btn btn-danger float-right"href="{{ route('medicalSpecialties.create') }}">Ajouter un Service</a>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
        <section class="section">
            <div class="card">
                @include('medical_specialties.table')
            </div>
        </section>
    </div>

@endsection

resources/views/medical_specialties/show.blade.php
@extends('BackOffice_layouts.master')

@section('title')
    Nos Services Médicaux | {{ config('app.name') }}
@endsection

@section('content')

    <div class="page-heading">
        <div class="page-title">
            <div class="row">
                <div class="col-12 col-md-6 order-md-1 order-last">
                    <h3 style="color: white !important">Détails du Service</h3>
                </div>
                <div class="col-12 col-md-6 order-md-2 order-first">
                    <nav aria-label="breadcrumb" class="breadcrumb-header float-start float-lg-end">
                        <ol class="breadcrumb">
                            <a class="btn btn-danger float-right"href="{{ route('medicalSpecialties.index') }}">Retour</a>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>

        <div class="content px-3">
            <div class="card">
                <div class="card-body">
                    @include('medical_specialties.show_fields')
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/medical_specialties/show_fields.blade.php
<div class="row">
    <!-- Title At Field -->
    <div class="col-md-6 col-12">
        <div class="form-group">
            {!! Form::label('title', 'Titre du Service:') !!}
            <p>{{ $medicalSpecialties->title }}</p>
        </div>
    </div>
    <!-- Slug At Field -->
    <div class="col-md-6 col-12">
        <div class="form-group">
            {!! Form::label('slug', 'slug:') !!}
            <p>{{ $medicalSpecialties->slug }}</p>
        </div>
    </div>
</div>

<div class="row mt-3">
    <!-- Description At Field -->
    <div class="col-md-12 col-12">
        <div class="form-group">
            {!! Form::label('description', 'Description du Service:') !!}
            <p>{!! $medicalSpecialties->description !!}</p>
        </div>
    </div>
</div>

<div class="row mt-3">
    <!-- Image At Field -->
    <div class="col-md-6 col-12">
        <div class="form-group">
            {!! Form::label('image', 'Image:') !!}
            <p><img src="{{ asset('/storage/images/' . $medicalSpecialties->image) }}" alt="" width="250" height="200"></p>
        </div>
    </div>
</div>

<div class="col-12 col-md-12 order-md-1 order-last">
    <h3 style="color: black !important">Précaution Avant l'Examen</h3>
</div>

<div class="row mt-3">
    <!-- Title At Field -->
    <div class="col-md-6 col-12">
        <div class="form-group">
            {!! Form::label('title', 'Titre du Service:') !!}
            <p>{{ $medicalSpecialties->title }}</p>
        </div>
    </div>
    <!-- Slug At Field -->
    <div class="col-md-6 col-12">
        <div class="form-group">
            {!! Form::label('slug', 'slug:') !!}
            <p>{{ $medicalSpecialties->slug }}</p>
        </div>
    </div>
</div>

<div class="col-12 col-md-12 order-md-1 order-last">
    <h3 style="color: black !important">Précaution Durant l'Examen</h3>
</div>

<div class="row mt-3">
    <!-- Title At Field -->
    <div class="col-md-6 col-12">
        <div class="form-group">
            {!! Form::label('title', 'Titre du Service:') !!}
            <p>{{ $medicalSpecialties->title }}</p>
        </div>
    </div>
    <!-- Slug At Field -->
    <div class="col-md-6 col-12">
        <div class="form-group">
            {!! Form::label('slug', 'slug:') !!}
            <p>{{ $medicalSpecialties->slug }}</p>
        </div>
    </div>
</div>

<div class="row mt-3">
    <!-- Created At Field -->
    <div class="col-md-6 col-12">
        <div class="form-group">
            {!! Form::label('created_at', 'Crée à:') !!}
            <p>{{ $medicalSpecialties->created_at }}</p>
        </div>
    </div>
    <!-- Updated At Field -->
    <div class="col-md-6 col-12">
        <div class="form-group">
            {!! Form::label('updated_at', 'Modifié à:') !!}
            <p>{{ $medicalSpecialties->updated_at }}</p>
        </div>
    </div>
</div>

resources/views/medical_specialties/table.blade.php
<div class="card-body">
    <table class="table table-striped" id="table1">
        <thead>
            <tr>
                <th>Image</th>
                <th>Nom du Service</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach($medicalSpecialties as $medicalSpecialties)
                <tr>

                    <td><img src="{{ asset('/storage/images/' .$medicalSpecialties->image) }}" alt="{{ $medicalSpecialties->title }}" width="90"></td>
                    <td>{{ $medicalSpecialties->title }}</td>
                    <td width="120">
                        {!! Form::open(['route' => ['medicalSpecialties.destroy', $medicalSpecialties->id], 'method' => 'delete']) !!}
                            <div class="btn-group mb-2" role="group" aria-label="Basic example">
                                <button type="button" class="btn btn-primary"><a href="{{ route('medicalSpecialties.show', [$medicalSpecialties->id]) }}" class='badge badge-pill badge-primary'>
                                    Voir
                                </a></button>
                                <button type="button" class="btn btn-warning"><a href="{{ route('medicalSpecialties.edit', [$medicalSpecialties->id]) }}" class='badge badge-pill badge-warning'>
                                    Editer
                                </a></button>
                                {!! Form::button('Supprimer', ['type' => 'submit', 'class' => 'btn btn-danger', 'onclick' => "return confirm('Are you sure?')"]) !!}
                            </div>
                        {!! Form::close() !!}
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
</div>