routes/web.php
<?php

use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Artisan::call('storage:link');

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', [App\Http\Controllers\FrontOfficeController::class, 'indexFrontOffice']);

Route::get('/contacter-nous', [App\Http\Controllers\FrontOfficeController::class, 'nousContacter'])->name('contacter-nous');

Route::get('/blog', [App\Http\Controllers\FrontOfficeController::class, 'indexBlog'])->name('blog');

Route::get('/detailblog/{slug}', [App\Http\Controllers\FrontOfficeController::class, "showBlog"]);

Route::get('/a-propos', [App\Http\Controllers\FrontOfficeController::class, 'indexAbout'])->name('a-propos');

Route::get('/prise-de-rendez-vous', [App\Http\Controllers\FrontOfficeController::class, 'appointmentPages'])->name('prise-de-rendez-vous');

Route::get('/irm', [App\Http\Controllers\FrontOfficeController::class, 'irmPage'])->name('irm');

Route::get('/biopsie', [App\Http\Controllers\FrontOfficeController::class, 'biopsiePage'])->name('biopsie');

Route::get('/echographie', [App\Http\Controllers\FrontOfficeController::class, 'echographiePage'])->name('echographie');

Route::get('/scanner', [App\Http\Controllers\FrontOfficeController::class, 'scannerPage'])->name('scanner');

Route::get('/mammographie', [App\Http\Controllers\FrontOfficeController::class, 'mammographiePage'])->name('mammographie');

Route::get('/radiographie', [App\Http\Controllers\FrontOfficeController::class, 'radiographiePage'])->name('radiographie');

Route::get('/bilan-sante', [App\Http\Controllers\FrontOfficeController::class, 'healhCheckPage'])->name('bilan-sante');

Route::get('/analyse-mediacale', [App\Http\Controllers\FrontOfficeController::class, 'medicalAnalysPage'])->name('analyse-mediacale');

Route::post('/footer', [App\Http\Controllers\NewslettersController::class, "addEmail"])->name('footer');

Route::post('/appointmentess', [App\Http\Controllers\AppointmentController::class, "SendAppointment"])->name('appointmentess');

Auth::routes([
    'register' => false, // Registration Routes...
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...
  ]);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::resource('slides', App\Http\Controllers\SlideController::class);

Route::resource('medicalSpecialties', App\Http\Controllers\MedicalSpecialtiesController::class);

Route::resource('appointments', App\Http\Controllers\AppointmentController::class);

Route::resource('blogs', App\Http\Controllers\BlogController::class);

Route::resource('newsletters', App\Http\Controllers\NewslettersController::class);

Route::resource('testimonials', App\Http\Controllers\TestimonialsController::class);

Route::resource('medicalCheckups', App\Http\Controllers\MedicalCheckupsController::class);

Route::resource('videoStores', App\Http\Controllers\VideoStoresController::class);

Route::post('ckeditor/upload', [App\Http\Controllers\CKEditorController::class, "upload"])->name('upload');

app/Models/MedicalCheckups.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

/**
 * Class MedicalCheckups
 * @package App\Models
 * @version June 9, 2021, 11:57 am UTC
 *
 */
class MedicalCheckups extends Model
{
    use SoftDeletes;

    use HasFactory;

    public $table = 'medical_checkups';


    protected $dates = ['deleted_at'];



    public $fillable = [
        'title',
        'slug'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'title' => 'string',
        'slug' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [

    ];

    public function getAppointmentAttribute()
    {
        return $this->hasMany(Appointment::class);
    }

}

app/Http/Controllers/MedicalCheckupsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateMedicalCheckupsRequest;
use App\Http\Requests\UpdateMedicalCheckupsRequest;
use App\Repositories\MedicalCheckupsRepository;
use App\Http\Controllers\AppBaseController;
use App\Models\MedicalCheckups;
use Illuminate\Http\Request;
use Flash;
use Response;

class MedicalCheckupsController extends AppBaseController
{
    /** @var  MedicalCheckupsRepository */
    private $medicalCheckupsRepository;

    public function __construct(MedicalCheckupsRepository $medicalCheckupsRepo)
    {
        $this->medicalCheckupsRepository = $medicalCheckupsRepo;
    }

    /**
     * Display a listing of the MedicalCheckups.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        // $medicalCheckups = $this->medicalCheckupsRepository->all();
        $medicalCheckups = MedicalCheckups::orderBy('id', 'desc')->paginate(10);

        return view('medical_checkups.index')
            ->with('medicalCheckups', $medicalCheckups);
    }

    /**
     * Show the form for creating a new MedicalCheckups.
     *
     * @return Response
     */
    public function create()
    {
        return view('medical_checkups.create');
    }

    /**
     * Store a newly created MedicalCheckups in storage.
     *
     * @param CreateMedicalCheckupsRequest $request
     *
     * @return Response
     */
    public function store(CreateMedicalCheckupsRequest $request)
    {
        $input = $request->all();

        $medicalCheckups = $this->medicalCheckupsRepository->create($input);

        Flash::success('Medical Checkups saved successfully.');

        return redirect(route('medicalCheckups.index'));
    }

    /**
     * Display the specified MedicalCheckups.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $medicalCheckups = $this->medicalCheckupsRepository->find($id);

        if (empty($medicalCheckups)) {
            Flash::error('Medical Checkups not found');

            return redirect(route('medicalCheckups.index'));
        }

        return view('medical_checkups.show')->with('medicalCheckups', $medicalCheckups);
    }

    /**
     * Show the form for editing the specified MedicalCheckups.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $medicalCheckups = $this->medicalCheckupsRepository->find($id);

        if (empty($medicalCheckups)) {
            Flash::error('Medical Checkups not found');

            return redirect(route('medicalCheckups.index'));
        }

        return view('medical_checkups.edit')->with('medicalCheckups', $medicalCheckups);
    }

    /**
     * Update the specified MedicalCheckups in storage.
     *
     * @param int $id
     * @param UpdateMedicalCheckupsRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateMedicalCheckupsRequest $request)
    {
        $medicalCheckups = $this->medicalCheckupsRepository->find($id);

        if (empty($medicalCheckups)) {
            Flash::error('Medical Checkups not found');

            return redirect(route('medicalCheckups.index'));
        }

        $medicalCheckups = $this->medicalCheckupsRepository->update($request->all(), $id);

        Flash::success('Medical Checkups updated successfully.');

        return redirect(route('medicalCheckups.index'));
    }

    /**
     * Remove the specified MedicalCheckups from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $medicalCheckups = $this->medicalCheckupsRepository->find($id);

        if (empty($medicalCheckups)) {
            Flash::error('Medical Checkups not found');

            return redirect(route('medicalCheckups.index'));
        }

        $this->medicalCheckupsRepository->delete($id);

        Flash::success('Medical Checkups deleted successfully.');

        return redirect(route('medicalCheckups.index'));
    }
}

resources/views/medical_checkups/create.blade.php
@extends('BackOffice_layouts.master_index')

@section('title')
    Nos Types d'Examens | {{ config('app.name') }}
@endsection

@section('content')

<div class="page-heading">
    <div class="page-title">
        <div class="row">
            <div class="col-12 col-md-6 order-md-1 order-last">
                <h3 style="color: white !important">Créer un Nouvel Examen</h3>
                <p class="text-subtitle text-muted" style="color: white !important">Les informations sur l'Examen</p>
            </div>
        </div>
    </div>

    <section id="basic-horizontal-layouts">
        <div class="row match-height">
            <div class="col-md-12 col-12">
                <div class="card">
                    <div class="card-content">
                        <div class="card-body">
                            {!! Form::open(['route' => 'medicalCheckups.store', 'class' => 'form', 'files' => true]) !!}
                                <div class="row">
                                    @include('medical_checkups.fields')
                                </div>
                            {!! Form::close() !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

</div>

@endsection

resources/views/medical_checkups/edit.blade.php
@extends('BackOffice_layouts.master_index')

@section('title')
    Nos Types d'examens | {{ config('app.name') }}
@endsection

@section('content')

    <div class="page-heading">
        <div class="page-title">
            <div class="row">
                <div class="col-12 col-md-6 order-md-1 order-last">
                    <h3 style="color: white !important">Modifier l'Examen</h3>
                    <p class="text-subtitle text-muted" style="color: white !important">Les informations sur l'Examen</p>
                </div>
            </div>
        </div>

        <section id="basic-horizontal-layouts">
            <div class="row match-height">
                <div class="col-md-12 col-12">
                    <div class="card">
                        <div class="card-content">
                            <div class="card-body">
                                {!! Form::model($medicalCheckups, ['route' => ['medicalCheckups.update', $medicalCheckups->id], 'method' => 'patch', 'files' => true]) !!}
                                    <div class="row">
                                        @include('medical_checkups.fields')
                                    </div>
                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

    </div>

@endsection

resources/views/medical_checkups/fields.blade.php
<!-- Title Field -->
<div class="col-md-6 col-12">
    <div class="form-group">
        {!! Form::label('title', 'Titre de l&rsquo;Examen:') !!}
        {!! Form::text('title', null, ['class' => 'form-control', 'placeholder' => 'Titre', 'onkeyup' => 'stringToSlug(this.value)']) !!}
    </div>
</div>

<!-- slug Field -->
<div class="col-md-6 col-12">
    <div class="form-group">
        {!! Form::label('slug', 'Slug:') !!}
        {!! Form::text('slug', null, ['class' => 'form-control', 'placeholder' => 'Slug', 'readonly']) !!}
    </div>
</div>

<div class="col-12 d-flex justify-content-end mt-3">
    {!! Form::submit('Enregistré', ['class' => 'btn btn-danger me-1 mb-1']) !!}
    <a href="{{ route('medicalCheckups.index') }}" class="btn btn-light-secondary me-1 mb-1">Annulé</a>
</div>

<script>
    function stringToSlug(str) {

        str = str.replace(/^\s+|\s+$/g, ''); // trim
        str = str.toLowerCase();

        // remove accents, swap ñ for n, etc
        var from = "àáäâèéëêìíïîòóöôùúüûñç·/_,:;";
        var to = "aaaaeeeeiiiioooouuuunc------";
        for (var i = 0, l = from.length; i < l; i++) {
            str = str.replace(new RegExp(from.charAt(i), 'g'), to.charAt(i));
        }

        str = str.replace(/[^a-z0-9 -]/g, '') // remove invalid chars
            .replace(/\s+/g, '-') // collapse whitespace and replace by -
            .replace(/-+/g, '-'); // collapse dashes

        // return str;
        document.getElementById("slug").value = str;
    }

    function showPercentage(val){
        if(val == 1){
            document.getElementById("div_percentage").style.display= 'block';
        }else{
            document.getElementById("div_percentage").style.display= 'none';
        }
    }

    function showSold(val){
        if(val == 1){
            document.getElementById("div_sold").style.display= 'block';
        }else{
            document.getElementById("div_sold").style.display= 'none';
        }
    }
</script>

resources/views/medical_checkups/index.blade.php
@extends('BackOffice_layouts.master_index')

@section('title')
    Nos Types d'Examens | {{ config('app.name') }}
@endsection

@section('content')

    <div class="page-heading">
        <div class="page-title">
            <div class="row">
                <div class="col-12 col-md-6 order-md-1 order-last">
                    <h3 style="color: white !important">Nos Types d'Examens</h3>
                    <p class="text-subtitle text-muted" style="color: white !important">La liste de tous nos Types d'Examens</p>
                </div>
                <div class="col-12 col-md-6 order-md-2 order-first">
                    <nav aria-label="breadcrumb" class="breadcrumb-header float-start float-lg-end">
                        <ol class="breadcrumb">
                            <a class="btn btn-danger float-right"href="{{ route('medicalCheckups.create') }}">Ajouter un Examen</a>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
        <section class="section">
            <div class="card">
                @include('medical_checkups.table')
            </div>
        </section>
    </div>

@endsection

resources/views/medical_checkups/show.blade.php
@extends('BackOffice_layouts.master')

@section('title')
    Nos Types d'Examens | {{ config('app.name') }}
@endsection

@section('content')

    <div class="page-heading">
        <div class="page-title">
            <div class="row">
                <div class="col-12 col-md-6 order-md-1 order-last">
                    <h3 style="color: white !important">Détails de L'Examen</h3>
                </div>
                <div class="col-12 col-md-6 order-md-2 order-first">
                    <nav aria-label="breadcrumb" class="breadcrumb-header float-start float-lg-end">
                        <ol class="breadcrumb">
                            <a class="btn btn-danger float-right"href="{{ route('medicalCheckups.index') }}">Retour</a>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>

        <div class="content px-3">
            <div class="card">
                <div class="card-body">
                    @include('medical_checkups.show_fields')
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/medical_checkups/show_fields.blade.php
<div class="row">
    <!-- Title At Field -->
    <div class="col-md-6 col-12">
        <div class="form-group">
            {!! Form::label('title', 'Titre de l&rsquo;Examen:') !!}
            <p>{{ $medicalCheckups->title }}</p>
        </div>
    </div>
    <!-- Slug At Field -->
    <div class="col-md-6 col-12">
        <div class="form-group">
            {!! Form::label('slug', 'slug:') !!}
            <p>{{ $medicalCheckups->slug }}</p>
        </div>
    </div>
</div>

<div class="row mt-3">
    <!-- Created At Field -->
    <div class="col-md-6 col-12">
        <div class="form-group">
            {!! Form::label('created_at', 'Crée à:') !!}
            <p>{{ $medicalCheckups->created_at }}</p>
        </div>
    </div>
    <!-- Updated At Field -->
    <div class="col-md-6 col-12">
        <div class="form-group">
            {!! Form::label('updated_at', 'Modifié à:') !!}
            <p>{{ $medicalCheckups->updated_at }}</p>
        </div>
    </div>
</div>

resources/views/medical_checkups/table.blade.php
<div class="card-body">
    <table class="table table-striped" id="table1">
        <thead>
            <tr>
                <th>Nom de l'Examen</th>
                <th>le Slug</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach($medicalCheckups as $medicalCheckups)
                <tr>

                    <td>{{ $medicalCheckups->title }}</td>
                    <td>{{ $medicalCheckups->slug }}</td>
                    <td width="120">
                        {!! Form::open(['route' => ['medicalCheckups.destroy', $medicalCheckups->id], 'method' => 'delete']) !!}
                            <div class="btn-group mb-2" role="group" aria-label="Basic example">
                                <button type="button" class="btn btn-primary"><a href="{{ route('medicalCheckups.show', [$medicalCheckups->id]) }}" class='badge badge-pill badge-primary'>
                                    Voir
                                </a></button>
                                <button type="button" class="btn btn-warning"><a href="{{ route('medicalCheckups.edit', [$medicalCheckups->id]) }}" class='badge badge-pill badge-warning'>
                                    Editer
                                </a></button>
                                {!! Form::button('Supprimer', ['type' => 'submit', 'class' => 'btn btn-danger', 'onclick' => "return confirm('Are you sure?')"]) !!}
                            </div>
                        {!! Form::close() !!}
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
</div>