routes/web.php
<?php

use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Artisan::call('storage:link');

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', [App\Http\Controllers\FrontOfficeController::class, 'indexFrontOffice']);

Route::get('/contacter-nous', [App\Http\Controllers\FrontOfficeController::class, 'nousContacter'])->name('contacter-nous');

Route::get('/blog', [App\Http\Controllers\FrontOfficeController::class, 'indexBlog'])->name('blog');

Route::get('/detailblog/{slug}', [App\Http\Controllers\FrontOfficeController::class, "showBlog"]);

Route::get('/a-propos', [App\Http\Controllers\FrontOfficeController::class, 'indexAbout'])->name('a-propos');

Route::get('/prise-de-rendez-vous', [App\Http\Controllers\FrontOfficeController::class, 'appointmentPages'])->name('prise-de-rendez-vous');

Route::get('/irm', [App\Http\Controllers\FrontOfficeController::class, 'irmPage'])->name('irm');

Route::get('/biopsie', [App\Http\Controllers\FrontOfficeController::class, 'biopsiePage'])->name('biopsie');

Route::get('/echographie', [App\Http\Controllers\FrontOfficeController::class, 'echographiePage'])->name('echographie');

Route::get('/scanner', [App\Http\Controllers\FrontOfficeController::class, 'scannerPage'])->name('scanner');

Route::get('/mammographie', [App\Http\Controllers\FrontOfficeController::class, 'mammographiePage'])->name('mammographie');

Route::get('/radiographie', [App\Http\Controllers\FrontOfficeController::class, 'radiographiePage'])->name('radiographie');

Route::get('/bilan-sante', [App\Http\Controllers\FrontOfficeController::class, 'healhCheckPage'])->name('bilan-sante');

Route::get('/analyse-mediacale', [App\Http\Controllers\FrontOfficeController::class, 'medicalAnalysPage'])->name('analyse-mediacale');

Route::post('/footer', [App\Http\Controllers\NewslettersController::class, "addEmail"])->name('footer');

Route::post('/appointmentess', [App\Http\Controllers\AppointmentController::class, "SendAppointment"])->name('appointmentess');

Auth::routes([
    'register' => false, // Registration Routes...
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...
  ]);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::resource('slides', App\Http\Controllers\SlideController::class);

Route::resource('medicalSpecialties', App\Http\Controllers\MedicalSpecialtiesController::class);

Route::resource('appointments', App\Http\Controllers\AppointmentController::class);

Route::resource('blogs', App\Http\Controllers\BlogController::class);

Route::resource('newsletters', App\Http\Controllers\NewslettersController::class);

Route::resource('testimonials', App\Http\Controllers\TestimonialsController::class);

Route::resource('medicalCheckups', App\Http\Controllers\MedicalCheckupsController::class);

Route::resource('videoStores', App\Http\Controllers\VideoStoresController::class);

Route::post('ckeditor/upload', [App\Http\Controllers\CKEditorController::class, "upload"])->name('upload');

app/Models/VideoStores.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

/**
 * Class VideoStores
 * @package App\Models
 * @version June 9, 2021, 11:58 am UTC
 *
 */
class VideoStores extends Model
{
    use SoftDeletes;

    use HasFactory;

    public $table = 'video_stores';


    protected $dates = ['deleted_at'];



    public $fillable = [
        'title',
        'subtitle',
        'link_youtube'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'title' => 'string',
        'subtitle' => 'string',
        'link_youtube' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [

    ];


}

app/Http/Controllers/VideoStoresController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateVideoStoresRequest;
use App\Http\Requests\UpdateVideoStoresRequest;
use App\Repositories\VideoStoresRepository;
use App\Http\Controllers\AppBaseController;
use App\Models\VideoStores;
use Illuminate\Http\Request;
use Flash;
use Response;

class VideoStoresController extends AppBaseController
{
    /** @var  VideoStoresRepository */
    private $videoStoresRepository;

    public function __construct(VideoStoresRepository $videoStoresRepo)
    {
        $this->videoStoresRepository = $videoStoresRepo;
    }

    /**
     * Display a listing of the VideoStores.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $videoStores = VideoStores::orderBy('id', 'desc')->paginate(10);
        // $videoStores = $this->videoStoresRepository->all();

        return view('video_stores.index')
            ->with('videoStores', $videoStores);
    }

    /**
     * Show the form for creating a new VideoStores.
     *
     * @return Response
     */
    public function create()
    {
        return view('video_stores.create');
    }

    /**
     * Store a newly created VideoStores in storage.
     *
     * @param CreateVideoStoresRequest $request
     *
     * @return Response
     */
    public function store(CreateVideoStoresRequest $request)
    {
        $input = $request->all();

        if(!is_null($input['link_youtube'])){
            $input['link_youtube'] = 'https://www.youtube.com/embed/'.$input['link_youtube'];
        }

        $videoStores = $this->videoStoresRepository->create($input);

        Flash::success('Video Stores saved successfully.');

        return redirect(route('videoStores.index'));
    }

    /**
     * Display the specified VideoStores.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $videoStores = $this->videoStoresRepository->find($id);

        if (empty($videoStores)) {
            Flash::error('Video Stores not found');

            return redirect(route('videoStores.index'));
        }

        return view('video_stores.show')->with('videoStores', $videoStores);
    }

    /**
     * Show the form for editing the specified VideoStores.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $videoStores = $this->videoStoresRepository->find($id);

        if (empty($videoStores)) {
            Flash::error('Video Stores not found');

            return redirect(route('videoStores.index'));
        }

        return view('video_stores.edit')->with('videoStores', $videoStores);
    }

    /**
     * Update the specified VideoStores in storage.
     *
     * @param int $id
     * @param UpdateVideoStoresRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateVideoStoresRequest $request)
    {
        $videoStores = $this->videoStoresRepository->find($id);

        if (empty($videoStores)) {
            Flash::error('Video Stores not found');

            return redirect(route('videoStores.index'));
        }

        $videoStores = $this->videoStoresRepository->update($request->all(), $id);

        Flash::success('Video Stores updated successfully.');

        return redirect(route('videoStores.index'));
    }

    /**
     * Remove the specified VideoStores from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $videoStores = $this->videoStoresRepository->find($id);

        if (empty($videoStores)) {
            Flash::error('Video Stores not found');

            return redirect(route('videoStores.index'));
        }

        $this->videoStoresRepository->delete($id);

        Flash::success('Video Stores deleted successfully.');

        return redirect(route('videoStores.index'));
    }
}

resources/views/video_stores/create.blade.php
@extends('BackOffice_layouts.master_index')

@section('title')
    Notre Vidéothèque | {{ config('app.name') }}
@endsection

@section('content')

<div class="page-heading">
    <div class="page-title">
        <div class="row">
            <div class="col-12 col-md-6 order-md-1 order-last">
                <h3 style="color: white !important">Ajouter une nouvelle Vidéo</h3>
                <p class="text-subtitle text-muted" style="color: white !important">Les informations sur la Vidéo</p>
            </div>
        </div>
    </div>

    <section id="basic-horizontal-layouts">
        <div class="row match-height">
            <div class="col-md-12 col-12">
                <div class="card">
                    <div class="card-content">
                        <div class="card-body">
                            {!! Form::open(['route' => 'videoStores.store', 'class' => 'form', 'files' => true]) !!}
                                <div class="row">
                                    @include('video_stores.fields')
                                </div>
                            {!! Form::close() !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

</div>

@endsection

resources/views/video_stores/edit.blade.php
@extends('BackOffice_layouts.master_index')

@section('title')
    Notre Vidéothèque  | {{ config('app.name') }}
@endsection

@section('content')

    <div class="page-heading">
        <div class="page-title">
            <div class="row">
                <div class="col-12 col-md-6 order-md-1 order-last">
                    <h3 style="color: white !important">Modifier la Vidéo</h3>
                    <p class="text-subtitle text-muted" style="color: white !important">Les informations sur la Vidéo</p>
                </div>
            </div>
        </div>

        <section id="basic-horizontal-layouts">
            <div class="row match-height">
                <div class="col-md-12 col-12">
                    <div class="card">
                        <div class="card-content">
                            <div class="card-body">
                                {!! Form::model($videoStores, ['route' => ['videoStores.update', $videoStores->id], 'method' => 'patch', 'files' => true]) !!}
                                    <div class="row">
                                        @include('video_stores.fields')
                                    </div>
                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

    </div>

@endsection

resources/views/video_stores/fields.blade.php
<!-- Title Field -->
<div class="col-md-4 col-12">
    <div class="form-group">
        {!! Form::label('title', 'Titre :') !!}
        {!! Form::text('title', null, ['class' => 'form-control', 'placeholder' => 'Titre']) !!}
    </div>
</div>

<!-- SubTitle Field -->
<div class="col-md-4 col-12">
    <div class="form-group">
        {!! Form::label('subtitle', 'Sous-Titre:') !!}
        {!! Form::text('subtitle', null, ['class' => 'form-control', 'placeholder' => 'Sous-Titre']) !!}
    </div>
</div>

<!-- link_youtube Field -->
<div class="col-md-4 col-12">
    <div class="form-group">
        {!! Form::label('link_youtube', 'Lien Youtube:') !!}
        {!! Form::text('link_youtube', null, ['class' => 'form-control', 'placeholder' => 'Lien Youtube']) !!}
        <small>Exemple: pour le lien suivant https://www.youtube.com/watch?v=mmq5zZfmIws vous devrez enregistrer l'id de la video qui est <strong>"mmq5zZfmIws"</strong></small>
    </div>
</div>

<div class="col-12 d-flex justify-content-end mt-3">
    {!! Form::submit('Enregistré', ['class' => 'btn btn-danger me-1 mb-1']) !!}
    <a href="{{ route('videoStores.index') }}" class="btn btn-light-secondary me-1 mb-1">Annulé</a>
</div>

resources/views/video_stores/index.blade.php
@extends('BackOffice_layouts.master_index')

@section('title')
    Notre Vidéothèque | {{ config('app.name') }}
@endsection

@section('content')

    <div class="page-heading">
        <div class="page-title">
            <div class="row">
                <div class="col-12 col-md-6 order-md-1 order-last">
                    <h3 style="color: white !important">Notre Vidéothèque </h3>
                    <p class="text-subtitle text-muted" style="color: white !important">La liste de toutes nos Vidéos</p>
                </div>
                <div class="col-12 col-md-6 order-md-2 order-first">
                    <nav aria-label="breadcrumb" class="breadcrumb-header float-start float-lg-end">
                        <ol class="breadcrumb">
                            <a class="btn btn-danger float-right"href="{{ route('videoStores.create') }}">Ajouter une Vidéo</a>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
        <section class="section">
            <div class="card">
                @include('video_stores.table')
            </div>
        </section>
    </div>

@endsection

resources/views/video_stores/show.blade.php
@extends('BackOffice_layouts.master')

@section('title')
    Notre Vidéothèque | {{ config('app.name') }}
@endsection

@section('content')

    <div class="page-heading">
        <div class="page-title">
            <div class="row">
                <div class="col-12 col-md-6 order-md-1 order-last">
                    <h3 style="color: white !important">Détails de la Vidéo</h3>
                </div>
                <div class="col-12 col-md-6 order-md-2 order-first">
                    <nav aria-label="breadcrumb" class="breadcrumb-header float-start float-lg-end">
                        <ol class="breadcrumb">
                            <a class="btn btn-warning float-right"href="{{ route('videoStores.index') }}">Retour</a>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>

        <div class="content px-3">
            <div class="card">
                <div class="card-body">
                    @include('video_stores.show_fields')
                </div>

            </div>
        </div>
    </div>
@endsection

resources/views/video_stores/show_fields.blade.php
<div class="row">
    <!-- Title At Field -->
    <div class="col-md-6 col-12">
        <div class="form-group">
            {!! Form::label('title', 'Titre de la Vidéo:') !!}
            <p>{{ $videoStores->title }}</p>
        </div>
    </div>
    <!-- Subtitle At Field -->
    <div class="col-md-6 col-12">
        <div class="form-group">
            {!! Form::label('subtitle', 'Sous-Titre:') !!}
            <p>{{ $videoStores->subtitle }}</p>
        </div>
    </div>
</div>

<div class="row">
    <!-- link_youtube At Field -->
    <div class="col-md-12 col-12">
        <div class="form-group">
            {!! Form::label('link_youtube', 'Lien de la Vidéo:') !!}
            <p>{{ $videoStores->link_youtube }}</p>
            <iframe class="embed-responsive-item" src="{{ $videoStores->link_youtube }}"></iframe>
        </div>
    </div>
</div>

<div class="row mt-3">
    <!-- Created At Field -->
    <div class="col-md-6 col-12">
        <div class="form-group">
            {!! Form::label('created_at', 'Crée à:') !!}
            <p>{{ $videoStores->created_at }}</p>
        </div>
    </div>
    <!-- Updated At Field -->
    <div class="col-md-6 col-12">
        <div class="form-group">
            {!! Form::label('updated_at', 'Modifié à:') !!}
            <p>{{ $videoStores->updated_at }}</p>
        </div>
    </div>
</div>

resources/views/video_stores/table.blade.php
<div class="card-body">
    <table class="table table-striped" id="table1">
        <thead>
            <tr>
                <th>Titre</th>
                <th>Sous-Titre</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach($videoStores as $videoStores)
                <tr>

                    <td>{{ $videoStores->title }}</td>
                    <td>{{ $videoStores->subtitle }}</td>
                    <td width="120">
                        {!! Form::open(['route' => ['videoStores.destroy', $videoStores->id], 'method' => 'delete']) !!}
                            <div class="btn-group mb-2" role="group" aria-label="Basic example">
                                <button type="button" class="btn btn-primary"><a href="{{ route('videoStores.show', [$videoStores->id]) }}" class='badge badge-pill badge-primary'>
                                    Voir
                                </a></button>
                                <button type="button" class="btn btn-warning"><a href="{{ route('videoStores.edit', [$videoStores->id]) }}" class='badge badge-pill badge-warning'>
                                    Editer
                                </a></button>
                                {!! Form::button('Supprimer', ['type' => 'submit', 'class' => 'btn btn-danger', 'onclick' => "return confirm('Are you sure?')"]) !!}
                            </div>
                        {!! Form::close() !!}
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
</div>