routes/web.php
<?php

use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Artisan::call('storage:link');

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', [App\Http\Controllers\FrontOfficeController::class, 'indexFrontOffice']);

Route::get('/contacter-nous', [App\Http\Controllers\FrontOfficeController::class, 'nousContacter'])->name('contacter-nous');

Route::get('/blog', [App\Http\Controllers\FrontOfficeController::class, 'indexBlog'])->name('blog');

Route::get('/detailblog/{slug}', [App\Http\Controllers\FrontOfficeController::class, "showBlog"]);

Route::get('/a-propos', [App\Http\Controllers\FrontOfficeController::class, 'indexAbout'])->name('a-propos');

Route::get('/prise-de-rendez-vous', [App\Http\Controllers\FrontOfficeController::class, 'appointmentPages'])->name('prise-de-rendez-vous');

Route::get('/irm', [App\Http\Controllers\FrontOfficeController::class, 'irmPage'])->name('irm');

Route::get('/biopsie', [App\Http\Controllers\FrontOfficeController::class, 'biopsiePage'])->name('biopsie');

Route::get('/echographie', [App\Http\Controllers\FrontOfficeController::class, 'echographiePage'])->name('echographie');

Route::get('/scanner', [App\Http\Controllers\FrontOfficeController::class, 'scannerPage'])->name('scanner');

Route::get('/mammographie', [App\Http\Controllers\FrontOfficeController::class, 'mammographiePage'])->name('mammographie');

Route::get('/radiographie', [App\Http\Controllers\FrontOfficeController::class, 'radiographiePage'])->name('radiographie');

Route::get('/bilan-sante', [App\Http\Controllers\FrontOfficeController::class, 'healhCheckPage'])->name('bilan-sante');

Route::get('/analyse-mediacale', [App\Http\Controllers\FrontOfficeController::class, 'medicalAnalysPage'])->name('analyse-mediacale');

Route::post('/footer', [App\Http\Controllers\NewslettersController::class, "addEmail"])->name('footer');

Route::post('/appointmentess', [App\Http\Controllers\AppointmentController::class, "SendAppointment"])->name('appointmentess');

Auth::routes([
    'register' => false, // Registration Routes...
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...
  ]);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::resource('slides', App\Http\Controllers\SlideController::class);

Route::resource('medicalSpecialties', App\Http\Controllers\MedicalSpecialtiesController::class);

Route::resource('appointments', App\Http\Controllers\AppointmentController::class);

Route::resource('blogs', App\Http\Controllers\BlogController::class);

Route::resource('newsletters', App\Http\Controllers\NewslettersController::class);

Route::resource('testimonials', App\Http\Controllers\TestimonialsController::class);

Route::resource('medicalCheckups', App\Http\Controllers\MedicalCheckupsController::class);

Route::resource('videoStores', App\Http\Controllers\VideoStoresController::class);

Route::post('ckeditor/upload', [App\Http\Controllers\CKEditorController::class, "upload"])->name('upload');

resources/views/BackOffice_layouts/footer.blade.php
<footer>
    <div class="footer clearfix mb-0 text-muted">
        <div class="float-start">
            <p>2021 &copy; CIRAD 2021</p>
        </div>
        <div class="float-end">
            <p>Crafted with <span class="text-danger"><i class="bi bi-heart-fill icon-mid"></i></span> by <a target="_blank" href="https://vanessalecosson.net/prestations-digitales/">INTERACTIVCO</a></p>
        </div>
    </div>
</footer>

resources/views/BackOffice_layouts/master.blade.php
<!doctype html>

<html   >

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>
    <link rel="icon" href="{{asset('assets/images/favicon.ico')}}" sizes="86x86" >

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;600;700;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{asset('assets/css/bootstrap.css')}}">

    <link rel="stylesheet" href="{{asset('assets/vendors/perfect-scrollbar/perfect-scrollbar.css')}}">
    <link rel="stylesheet" href="{{asset('assets/vendors/bootstrap-icons/bootstrap-icons.css')}}">
    <link rel="stylesheet" href="{{asset('assets/css/app.css')}}">

    <link rel="stylesheet" href="{{asset('assets/vendors/iconly/bold.css')}}">
    <link rel="shortcut icon" href="assets/images/favicon.svg" type="image/x-icon">

</head>
<body>
    <div id="app">

        <div id="sidebar" class="active">

            @include('BackOffice_layouts.sidebar')

        </div>

        <div id="main" class='layout-navbar'>

            <header class='mb-3'>

                @include('BackOffice_layouts.navbar')

            </header>

            <div id="main-content">

                @yield('content')

                @include('BackOffice_layouts.footer')
            </div>

        </div>

    </div>

    <script src="{{asset('assets/vendors/apexcharts/apexcharts.js')}}"></script>
    <script src="{{asset('assets/js/pages/dashboard.js')}}"></script>
    <script src="{{asset('assets/vendors/perfect-scrollbar/perfect-scrollbar.min.js')}}"></script>
    <script src="{{asset('assets/js/bootstrap.bundle.min.js')}}"></script>
    <script src="{{asset('assets/js/main.js')}}"></script>
</body>
</html>

resources/views/BackOffice_layouts/master_index.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@yield('title')</title>

    <link rel="icon" href="{{asset('assets/images/favicon.ico')}}" >

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;600;700;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{asset('assets/css/bootstrap.css')}}">

    <link rel="stylesheet" href="{{asset('assets/vendors/choices.js/choices.min.css')}}">
    <link rel="stylesheet" href="{{asset('assets/vendors/simple-datatables/style.css')}}">

    <link rel="stylesheet" href="{{asset('assets/vendors/perfect-scrollbar/perfect-scrollbar.css')}}">
    <link rel="stylesheet" href="{{asset('assets/vendors/bootstrap-icons/bootstrap-icons.css')}}">
    <link rel="stylesheet" href="{{asset('assets/css/app.css')}}">
</head>

<body>

    <div id="app">

        <div id="sidebar" class="active">

            @include('BackOffice_layouts.sidebar')

        </div>

        <div id="main" class='layout-navbar'>

            <header class='mb-3'>

                @include('BackOffice_layouts.navbar')

            </header>
        </div>

        <div id="main">

            @yield('content')

            @include('BackOffice_layouts.footer')
        </div>

    </div>

    <script src="https://cdn.ckeditor.com/4.16.0/standard/ckeditor.js"></script>
    <script src="{{asset('assets/vendors/perfect-scrollbar/perfect-scrollbar.min.js')}}"></script>
    <script src="{{asset('assets/js/bootstrap.bundle.min.js')}}"></script>

    <script src="{{asset('assets/vendors/simple-datatables/simple-datatables.js')}}"></script>
    <script src="{{asset('assets/vendors/choices.js/choices.min.js')}}"></script>
    <script>
        // Simple Datatable
        let table1 = document.querySelector('#table1');
        let dataTable = new simpleDatatables.DataTable(table1);
    </script>

    <script type="text/javascript">
        CKEDITOR.replace('description', {
            filebrowserUploadUrl: "{{route('upload', ['_token' => csrf_token() ])}}",
            filebrowserUploadMethod: 'form'
        });
    </script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('.description').ckeditor();
        });
        $in['force_p_newlines'] = FALSE;
    </script>

    <script src="{{asset('assets/js/main.js')}}"></script>

</body>

</html>

resources/views/BackOffice_layouts/navbar.blade.php
<nav class="navbar navbar-expand navbar-light ">
    <div class="container-fluid">
        <a href="#" class="burger-btn d-block">
            <i class="bi bi-justify fs-3"></i>
        </a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item dropdown me-3">
                    {{-- <a class="nav-link active dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">
                        {{-- <i class='bi bi-bell bi-sub fs-4 text-gray-600'></i> --}}
                    {{-- </a>  --}}
                    {{-- <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuButton">
                        <li>
                            <h6 class="dropdown-header">Notifications</h6>
                        </li>
                        <li><a class="dropdown-item">No notification available</a></li>
                    </ul> --}}
                </li>
            </ul>
            <div class="dropdown">
                <!-- Authentication Links -->
                @guest
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                </li>
                @if (Route::has('register'))
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                    </li>
                @endif
                @else
                    <a href="#" data-bs-toggle="dropdown" aria-expanded="false">
                        <div class="user-menu d-flex">
                            <div class="user-name text-end me-3">
                                <h6 class="mb-0 text-gray-600"> {{ Auth::user()->name }}</h6>
                                <p class="mb-0 text-sm text-gray-600">Administrator</p>
                            </div>
                            <div class="user-img d-flex align-items-center">
                                <div class="avatar avatar-md">
                                    <img src="{{asset('assets/images/1.jpg')}}">
                                </div>
                            </div>
                        </div>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuButton">
                        <li><a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
                            document.getElementById('logout-form').submit();"><i
                            class="icon-mid bi bi-box-arrow-left me-2"></i> Deconnexion</a>
                            <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                @csrf
                            </form>
                        </li>
                    </ul>
                @endguest
            </div>
        </div>
    </div>
</nav>

resources/views/BackOffice_layouts/sidebar.blade.php
<div class="sidebar-wrapper active">
    <div class="sidebar-header">
        <div class="d-flex justify-content-between">
            <div class="logo">
                <a href="{{url('/') }}"><img src="{{asset('assets/images/logo.jpg')}}" alt="Logo" srcset=""></a>
            </div>
            <div class="toggler">
                <a href="#" class="sidebar-hide d-xl-none d-block"><i class="bi bi-x bi-middle"></i></a>
            </div>
        </div>
    </div>
    <div class="sidebar-menu">
        <ul class="menu">
            <li class="sidebar-item {{ Request::is('home*') ? 'active' : '' }}">
                <a href="{{ route('home') }}" class='sidebar-link'>
                    <i class="bi bi-grid-fill"></i>
                    <span>Dashboard</span>
                </a>
            </li>
            {{-- <li class="sidebar-item {{ Request::is('medicalSpecialties*') ? 'active' : '' }}">
                <a href="{{ route('medicalSpecialties.index') }}" class='sidebar-link'>
                    <i class="bi bi-stack"></i>
                    <span>Nos Services</span>
                </a>
            </li> --}}
            <li class="sidebar-item {{ Request::is('appointments*') ? 'active' : '' }}">
                <a href="{{ route('appointments.index') }}" class='sidebar-link'>
                    <i class="bi bi-collection-fill"></i>
                    <span>Les Rendez-Vous</span>
                </a>
            </li>
            <li class="sidebar-item {{ Request::is('blogs*') ? 'active' : '' }}">
                <a href="{{ route('blogs.index') }}" class='sidebar-link'>
                    <i class="bi bi-grid-1x2-fill"></i>
                    <span>Le Blog</span>
                </a>
            </li>
            <li class="sidebar-item {{ Request::is('medicalCheckups*') ? 'active' : '' }}">
                <a href="{{ route('medicalCheckups.index') }}" class='sidebar-link'>
                    <i class="bi bi-hexagon-fill"></i>
                    <span>Les Types d'Exemens</span>
                </a>
            </li>
            <li class="sidebar-item {{ Request::is('newsletters*') ? 'active' : '' }}">
                <a href="{{ route('newsletters.index') }}" class='sidebar-link'>
                    <i class="bi bi-envelope-open-fill"></i>
                    <span>La NewsLetter</span>
                </a>
            </li>
            <li class="sidebar-item {{ Request::is('videoStores*') ? 'active' : '' }}">
                <a href="{{ route('videoStores.index') }}" class='sidebar-link'>
                    <i class="bi bi-people-fill"></i>
                    <span>Notre Vidéothèque</span>
                </a>
            </li>
            <li class="sidebar-item {{ Request::is('testimonials*') ? 'active' : '' }}">
                <a href="{{ route('testimonials.index') }}" class='sidebar-link'>
                    <i class="bi bi-pen-fill"></i>
                    <span>Les Témoignages</span>
                </a>
            </li>
            <li class="sidebar-item {{ Request::is('slides*') ? 'active' : '' }}">
                <a href="{{ route('slides.index') }}" class='sidebar-link'>
                    <i class="bi bi-grid-1x2-fill"></i>
                    <span>Gestion du Slide</span>
                </a>
            </li>
        </ul>
    </div>
    <button class="sidebar-toggler btn x"><i data-feather="x"></i></button>
</div>